//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexxtyDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Blogs = new HashSet<Blog>();
            }
        public int PostID { get; set; }
        public string Title { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string UrlField { get; set; }
        public bool Draft { get; set; }
        public string PostContent { get; set; }
        public int BlogID { get; set; }
        public int ViewCount { get; set; }
    
        public virtual Blog Blog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog> Blogs { get; set; }

    }
}
