//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexxtyDataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TexxtyDBEntities : DbContext
    {
        public TexxtyDBEntities()
            : base("name=TexxtyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogFollow> BlogFollows { get; set; }
        public virtual DbSet<BlogTopic> BlogTopics { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<TopicFollow> TopicFollows { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
